# currently I've just used defaults with salinity changed to 0.0
# and using ECMWF data if available
# these are the settings for resampling
resolution=10
down=Min
up=Bicubic
flag=First

# these are the settings for c2rcc
#validPix=B8 > 0 && B8 < 0.1
# try making all pixels valid regardless
validPix=true
# increase salinity to see what this does!
salinity=0.3
# lowest allowed value 2.8E-5
temp=15.0
ozone=330.0
press=1000.0
elevation=0.0
TSMfac=1.06
TSMexp=0.942
CHLexp=1.04
CHLfac=21.0
rtosaThresh=0.05
ACrefOOS=0.1
cloud865=0.955
NN_Set=C2X-Nets
# options are C2RCC-Nets, C2X-Nets, C2X-COMPLEX-Nets
outputAsRrs=true
# output as Rrs instead of rhow
deriveRwFromPathAndTransmittance=false 
useEcmwfAuxData=true
# use ECMWF data if available
outputRtoa=false
# output TOA reflectances
outputRtosaGc=false
# gas corrected tosa reflectances
outputRtosaGcAann=false
# gas corrected tosa reflectances of auto NN
outputRpath=false
# path radiance reflectances
outputTdown=false
# downwards transmittance
outputTup=false
# upward transmittance
outputAcReflectance=true
# atmospherically corrected angular dependant reflectances
outputRhown=true
# normalised water leaving reflectances
outputOos=false
# out of scope values
outputKd=true
# irradiance attenuation coeffs
outputUncertainties=true
